USE ROLE ACCOUNTADMIN;

-- Grant SYSADMIN role to user
GRANT ROLE SYSADMIN TO USER CICD_USER;
ALTER USER CICD_USER SET DEFAULT_ROLE = SYSADMIN;

-- Grant warehouse access to SYSADMIN
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SYSADMIN;

-- Grant database and schema access
GRANT USAGE ON DATABASE SPARK_NO_9 TO ROLE SYSADMIN;
GRANT USAGE ON SCHEMA SPARK_NO_9.PUBLIC TO ROLE SYSADMIN;
GRANT CREATE STREAMLIT ON SCHEMA SPARK_NO_9.PUBLIC TO ROLE SYSADMIN;
GRANT CREATE STAGE ON SCHEMA SPARK_NO_9.PUBLIC TO ROLE SYSADMIN;

-- Verify
SHOW GRANTS TO USER CICD_USER;

USE ROLE ACCOUNTADMIN;

-- Essential database permissions
GRANT USAGE ON DATABASE SPARK_NO_9 TO ROLE SYSADMIN;
GRANT MONITOR ON DATABASE SPARK_NO_9 TO ROLE SYSADMIN;
GRANT CREATE SCHEMA ON DATABASE SPARK_NO_9 TO ROLE SYSADMIN;

-- Essential schema permissions
GRANT USAGE ON SCHEMA SPARK_NO_9.PUBLIC TO ROLE SYSADMIN;
GRANT CREATE STREAMLIT ON SCHEMA SPARK_NO_9.PUBLIC TO ROLE SYSADMIN;
GRANT CREATE STAGE ON SCHEMA SPARK_NO_9.PUBLIC TO ROLE SYSADMIN;
GRANT CREATE TABLE ON SCHEMA SPARK_NO_9.PUBLIC TO ROLE SYSADMIN;
GRANT CREATE VIEW ON SCHEMA SPARK_NO_9.PUBLIC TO ROLE SYSADMIN;

-- Warehouse permissions
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SYSADMIN;
GRANT OPERATE ON WAREHOUSE COMPUTE_WH TO ROLE SYSADMIN;
GRANT MODIFY ON WAREHOUSE COMPUTE_WH TO ROLE SYSADMIN;




-- 1) Ensure the CICD role can use DB/Schema/Warehouse
USE ROLE ACCOUNTADMIN;

GRANT USAGE ON DATABASE SPARK_NO_9 TO ROLE SYSADMIN;
GRANT USAGE ON SCHEMA SPARK_NO_9.PUBLIC TO ROLE SYSADMIN;

GRANT CREATE STAGE ON SCHEMA SPARK_NO_9.PUBLIC TO ROLE SYSADMIN;
GRANT CREATE STREAMLIT ON SCHEMA SPARK_NO_9.PUBLIC TO ROLE SYSADMIN;
GRANT CREATE TABLE ON SCHEMA SPARK_NO_9.PUBLIC TO ROLE SYSADMIN;
GRANT CREATE VIEW  ON SCHEMA SPARK_NO_9.PUBLIC TO ROLE SYSADMIN;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SYSADMIN;

-- (Nice-to-have) future grants in this schema
GRANT ALL PRIVILEGES ON FUTURE TABLES    IN SCHEMA SPARK_NO_9.PUBLIC TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON FUTURE VIEWS     IN SCHEMA SPARK_NO_9.PUBLIC TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON FUTURE STAGES    IN SCHEMA SPARK_NO_9.PUBLIC TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON FUTURE STREAMLITS IN SCHEMA SPARK_NO_9.PUBLIC TO ROLE SYSADMIN;

-- 2) Make CICD user default to the right role/WH/namespace
ALTER USER CICD_USER SET DEFAULT_ROLE       = SYSADMIN;
ALTER USER CICD_USER SET DEFAULT_WAREHOUSE  = COMPUTE_WH;
ALTER USER CICD_USER SET DEFAULT_NAMESPACE  = "SPARK_NO_9"."PUBLIC";




GRANT OWNERSHIP ON DATABASE SPARK_NO_9 TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT READ, WRITE ON STAGE SPARK_NO_9.PUBLIC.streamlit_stage TO ROLE SYSADMIN;


USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE SPARK_NO_9;
USE SCHEMA PUBLIC;

